import{i as d,S as f}from"./assets/vendor-46aac873.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerpolicy&&(r.referrerPolicy=t.referrerpolicy),t.crossorigin==="use-credentials"?r.credentials="include":t.crossorigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();const p="42176661-60cd7e02e4c469a287416d2c6",c=document.querySelector(".photo-container-js");function g(){const o=document.createElement("div");o.className="loader",c.appendChild(o)}function l(){const o=c.querySelector(".loader");o&&o.remove()}function h(o){o.forEach(e=>{const n=`
      <li class="image-card">
      <a class="image-link" href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}"></a>
        <div class="image-details">
          <p class="detail">Likes ${e.likes}</p>
          <p class="detail">Views ${e.views}</p>
          <p class="detail">Comments ${e.comments}</p>
          <p class="detail">Downloads ${e.downloads}</p>
        </div>
      </li>
    `;c.insertAdjacentHTML("beforeend",n)})}function y(o){g();const e="photo",n="horizontal",i=!0,r=`https://pixabay.com/api/?${new URLSearchParams({key:p,q:o,image_type:e,orientation:n,safesearch:i})}`;fetch(r).then(s=>{if(!s.ok)throw new Error("Network response was not ok");return s.json()}).then(s=>{l();const m=document.getElementById("gallery");if(m.innerHTML="",parseInt(s.totalHits)>0){const u=s.hits.map(a=>({webformatURL:a.webformatURL,tags:a.tags,likes:a.likes,views:a.views,comments:a.comments,downloads:a.downloads,largeImageURL:a.largeImageURL}));h(u),new f(".image-card a",{captionsData:"alt"}).refresh()}else d.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topCenter"})}).catch(s=>{l(),console.error("Error during fetch:",s.message)})}document.addEventListener("DOMContentLoaded",function(){document.querySelector(".js-search-form").addEventListener("submit",function(o){o.preventDefault();const e=document.querySelector(".input").value;e.trim()!==""?y(e):d.error({message:"Please enter a valid search query.",position:"topRight"}),o.target.reset()})});
//# sourceMappingURL=commonHelpers.js.map
